homeassistant:

  name: Ming
  latitude: 37.0674
  longitude: 112.2423

  elevation: 790

  unit_system: metric

  time_zone: Asia/Chongqing

  customize: !include customize.yaml



# 是否使用默认的“首页”
frontend:
  themes:
    darkorange:
       primary-color: "#ff9800"
       light-primary-color: "#ffc947"
       dark-primary-color: "#c66900"
       text-primary-color: "#ffffff"
       primary-background-color: "#37464f"
       sidebar-text_-_background: "#62717b"
       paper-card-background-color: "#263137"
       paper-card-header-color: "var(--text-primary-color)"
       secondary-background-color: "var(--primary-background-color)"
       primary-text-color: "var(--text-primary-color)"
       secondary-text-color: "var(--primary-color)"
       paper-listbox-background-color: "var(--sidebar-text_-_background)"
       paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
       paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
       paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
       paper-slider-knob-color: "var(--primary-color)"
       paper-slider-knob-start-color: "var(--primary-color)"
       paper-slider-pin-color: "var(--primary-color)"
       paper-slider-active-color: "var(--primary-color)"
       paper-slider-secondary-color: "var(--light-primary-color)"
       paper-slider-container-color: "var(--sidebar-text_-_background)"
       paper-progress-secondary-color: "var(--sidebar-text_-_background)"
       paper-item-selected_-_background-color: "var(--primary-color)"
       paper-item-icon_-_color: "var(--text-primary-color)"
       paper-item-icon-color: "var(--sidebar-text_-_background)"
       paper-item-icon-active-color: "var(--primary-color)"
       paper-grey-50: "var(--sidebar-text_-_background)"
       paper-grey-200: "var(--primary-background-color)"
       label-badge-background-color: "var(--sidebar-text_-_background)"
       label-badge-text-color: "var(--text-primary-color)"
       label-badge-red: "var(--primary-color)"
       label-badge-blue: "var(--light-primary-color)"
       label-badge-green: "var(--dark-primary-color)"
       label-badge-yellow: "var(--text-primary-color)"
       label-badge-grey: "var(--paper-grey-500)"
       table-row-background-color: "var(--paper-card-background-color)"
      ## table-row-alternative-background-color: "var(--sidebar-text_-_background)”
    midnight:
      # Main colors
      primary-color: '#5294E2'                                                        # Header
      accent-color: '#E45E65'                                                         # Accent color
      dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks
      light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about

      # Text colors
      primary-text-color: '#FFFFFF'                                                   # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
      secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
      disabled-text-color: '#7F848E'                                                  # Disabled text colour
      label-badge-border-color: 'green'                                               # Label badge border, just a reference value

      # Background colors
      primary-background-color: '#383C45'                                             # Settings background
      secondary-background-color: '#383C45'                                           # Main card UI background
      divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider

      # Table rows
      table-row-background-color: '#353840'                                           # Table row
      table-row-alternative-background-color: '#3E424B'                               # Table row alternative

      # Nav Menu
      paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
      paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                                                       # Navigation menu selection

      # Paper card
      paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
      paper-card-background-color: '#434954'                                          # Card background colour
      paper-dialog-background-color: '#434954'                                        # Card dialog background colour
      paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
      paper-item-icon-active-color: '#F9C536'                                         # Icon color active
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'                               # Popup item select
      paper-tabs-selection-bar-color: 'green'

      # Labels
      label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
      label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
      label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here

      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'

      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'

      # Google colors
      google-red-500: '#E45E65'
      google-green-500: '#39E949'
    darkcyan:
    # Main colors that can be changed
      primary-color: "#00bcd4"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#4e4e4e"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      paper-listbox-color: "#FFFFFF"
      primary-background-color: "#303030"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#2b2b2b"
      secondary-text-color: "#04a7bc"
    # Colors based on variables, see above
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#var(--paper-item-icon-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
shell_command:
  getmusicurl: "python3 /home/pi/.homeassistant/script/get_music_url.py {{musicname}}"

http:
  # 给系统网页的登录加上一个密码 (推荐!)，先去掉下面这行的#号，然后把PASSWORD改成你想要的密码
  # api_password: PASSWORD

# 升级提示，当HomeAssitant有新版本发布的时候，“日出日落”图标会变成（Update）字样
updater:

# 系统自动发现新的设备
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:


# 在系统数据库中保存“历史数据”
history:

# 在logbook查看所有的“已发生事项”
logbook:

# 太阳“跟踪器”，也就是“日出日落时间”
sun:



#MQTT服务器的相关设置，除了username和password，没搞懂之前，别瞎改
mqtt:
  broker: 192.168.123.110
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: ming
  password: 9227
  protocol: 3.1.1

alarm_control_panel:
 platform: manual_mqtt
 state_topic: "home/alarm"
 command_topic: "home/alarm/set"
 name: Alarm


camera:
  # - name: 'room'
  #   platform: mjpeg
  #   mjpeg_url: http://192.168.123.58:8080/video

  - name: 'pi'
    platform: rpi_camera

climate:
  - platform: gree_other
    name: GREE
    host: 192.168.123.70
    mac: 34:EA:34:88:FF:9E
    target_sensor: sensor.Living_Room_Temp
    target_temp: 27

  - platform: midea
    name: Midea
    host: 192.168.123.70
    mac: 34:EA:34:88:FF:9E
    target_sensor: sensor.Living_Room_Temp
    target_temp: 27
#电视频道数字键

#
device_tracker:
  - platform: padavanwrt
    host: 192.168.123.1
    interval_seconds: 30
    consider_home: 180
    username: admin
    password: admin
    track_new_device: yes


binary_sensor :
  - platform: mqtt
    name: "mencitest"
    state_topic: "/ESP_01/switch/menci"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    device_class: opening

  - platform: mqtt
    name: "yudi"
    state_topic: "/ESP_01/switch/yudi"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    device_class: moisture


# switch 2:
# binary_sensor:
#   - platform: mqtt
#     state_topic: "home/Bed_room/Sonoff/motion"
#     name: "SONOFF PIR"
#     qos: 1
#     payload_off: "off"
#     payload_on: "on"
#     device_class: motion
#
media_player:
  - platform: vlc
    name: speaker
    arguments: '--alsa-audio-device=hw:0,0'

# notify:
#   - name: notify
#     platform: pushbullet
#     api_key: o.N5AVtoziBRZhQv5BPHTmsDUEb1yaJqkA

tts:
  - platform: baidu
    language: zh
    api_key: V9DsiGU27c6xYURo8jhLLu6W
    secret_key: 58b7331a1be8279207301c29eb974891
    speed: 3
    pitch: 9
    volume: 9
    person: 0

# 传感器1：天气“传感器”，API请到forecast.io网站注册并获得，然后填写好
ios:
sensor: !include sensors.yaml
light:  !include lights.yaml
switch: !include switchs.yaml
script: !include script.yaml
group: !include group.yaml
automation:  !include automations.yaml
config:
