- platform: mqtt
  name: "switch1"
  state_topic: "/ESP_02/Switch1/Control"
  command_topic: "/ESP_02/gpio/13"
  payload_on: "1"
  payload_off: "0"
  qos: 1
  retain: true

- platform: mqtt
  name: "switch2"
  state_topic: "/ESP_02/Switch2/Control"
  command_topic: "/ESP_02/gpio/15"
  payload_on: "1.0"
  payload_off: "0.0"
  optimistic: true
  qos: 1
  retain: true
  value_template: '{{ value.x }}'

- platform: mqtt
  name: "switch3"
  state_topic: "/ESP_01/switch1/Control"
  command_topic: "/ESP_01/gpio/13"
  payload_on: "1.0"
  payload_off: "0.0"
  optimistic: true
  qos: 1
  retain: true
  value_template: '{{ value.x }}'

- platform: mqtt
  name: "t1"
  state_topic: "home/8ch/2/stat"
  command_topic: "home/8ch/2"
  qos: 1
  payload_on: "1on"
  payload_off: "1off"
  retain: true
- platform: mqtt
  name: "t2"
  state_topic: "home/8ch/2/stat"
  command_topic: "home/8ch/2"
  qos: 1
  payload_on: "2on"
  payload_off: "2off"
  retain: true
- platform: mqtt
  name: "t3"
  state_topic: "home/8ch/2/stat"
  command_topic: "home/8ch/2"
  qos: 1
  payload_on: "3on"
  payload_off: "3off"
  retain: true
- platform: mqtt
  name: "t4"
  state_topic: "home/8ch/2/stat"
  command_topic: "home/8ch/2"
  qos: 1
  payload_on: "4on"
  payload_off: "4off"
  retain: true
- platform: mqtt
  name: "t5"
  state_topic: "home/8ch/2/stat"
  command_topic: "home/8ch/2"
  qos: 1
  payload_on: "5on"
  payload_off: "5off"
  retain: true
- platform: mqtt
  name: "t6"
  state_topic: "home/8ch/2/stat"
  command_topic: "home/8ch/2"
  qos: 1
  payload_on: "6on"
  payload_off: "6off"
  retain: true
